Select * from customer
--Q1 What is the total revenue generated by male vs female customers?
select gender , sum(purchase_amount) as revenue 
from customer
group by gender

--Q2 Which customers used a discount but still spent more than average purchase amout 

select customer_id , purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

-- Q3 Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg (review_rating::numeric),2) as "AVGreviewRating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4 Compare the average Purchase Amounts between Standard and Express Shipping

select round(avg(purchase_amount),2), shipping_type 
from customer
where shipping_type = 'Standard' or shipping_type = 'Express'
group by shipping_type

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers
select count(customer_id),round(avg(purchase_amount) ,2) as avg_pamount, subscription_status ,sum(purchase_amount) as tot_rev
from customer
where subscription_status = 'Yes' or subscription_status ='No'
group by subscription_status

-- Q6 Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) AS discount_rate
from customer 
group by item_purchased 
order by discount_rate desc 
limit 5;

-- Q7 Segment customers into New , Returning and Loyal based on their total number of previous purchases and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case when previous_purchases = '1' then 'new'
	when previous_purchases between 2 and 15 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer
)
select customer_segment,count (*) as "number of customers"
from customer_type
group by customer_segment

-- Q8 What are the top 3 most purchased products within each category ?

with item_counts as (
select item_purchased,category,count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)


select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
select subscription_status, count(customer_id) as cus
from customer

where previous_purchases > 5
group by subscription_status

--Q10 what is the revenue contribution of each age group?
select age_group, SUM(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc 

